/*
import 'package:get/get.dart';

class MyLocalization implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "appName": "",
          "engineer": "",
          "projectOwner": "",
          "emal": "",
          "phone": "",
          "password": "",
          "comfirmPassword": "",
          "signUp": "",
          "forgetPassword": "",
          "tabScreen": "",
          "addProjectScreen": "",
          "addProtofilo": "",
          "offerScreen": "",
          "paypal": "",
          "visa": "",
          "chatRoom": "",
          "addSomeProject": "",
          "notifcation": "",
          "profileUser": "",
          "profileEngineer": "",
          "support": "",
          "language": "",
          "noMessageYet": "",
          "noMessageSuppoerYet": "",
          "projectDetails": "",
          "editMyProject": "",
          "noData": "",
          "send": "",
          "exitApp": "",
          "chat": "",
          "myProject": "",
          "project": "",
          "price": "",
          "descreiption": "",
          "days": "",
          "home": "",
          "settings": "",
          "agreeTotermsOfServices": "",
          "lastName": "",
          "firstName": "",
          "signUpWithEmail": "",
          "timeOut": "",
          "tryAgain": "",
          "login": "",
          "chooseCategory":"",
          "history":"",
          "paymentHistory":"",
          "businessFair":"",
          "reviews":"",
          "personalProfile":"",
          "servicesDetail":"",
          "subServices":"",
          "faq":"",
          "logout":"",
          "privacyPolicy":"",
          "termsOfServices":"",
          "version":"",
          "profile":"",
          "noProjectYet":"",

          "search":"",
          "allOffer":"",
          "addOffer":"",
          "sendMessage":"",
          "submitYourProject":"",
        },
      };
}

  
  static const String businessFair = "Business Fair";
  static const String paymentHistory = "Payment History";
  static const String history = "History";
  static const String chooseCategory = "Choose a category";
  static const String search = "Search";
  static const String submitYourProject = "Submit Your Project";
  static const String sendMessage = "send message";
  static const String addOffer = "Add your offer now";
  static const String allOffer = "All offers";

*/
import 'package:get/get.dart';

import '../../app_config/app_config.dart';

class AppLocalization implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          AppConfig.appName: "اسم التطبيق",
          AppConfig.engineer: "المهندسين",
          AppConfig.projectOwner: "صاحب المشروع",
          AppConfig.emal: "الايميل",
          AppConfig.phone: "رقم الهاتف",
          AppConfig.password: "كلمة المرور",
          AppConfig.comfirmPassword: "تأكيد كلمة المرور",
          AppConfig.signUp: "انشاء حساب",
          AppConfig.forgetPassword: "نسيت كلمة المرور؟",
          AppConfig.tabScreen: "",
          AppConfig.addProjectScreen: "اضافة مشروع",
          AppConfig.addProtofilo: "اضافة مشروع الي معرض الاعمال",
          AppConfig.offerScreen: "",
          AppConfig.paypal: "بايبال",
          AppConfig.visa: "فيزا",
          AppConfig.chatRoom: "الدردشة",
          AppConfig.addSomeProject: "قم باضافة بعض المشاريع",
          AppConfig.notifcation: "الاشعارات",
          AppConfig.profileUser: "الملف الشخصي",
          AppConfig.profileEngineer: "معرص اعمال المهندسين",
          AppConfig.support: "الدعم الفني",
          AppConfig.language: "اللغة",
          AppConfig.noMessageYet: "لاتوجد رسائل",
          AppConfig.noMessageSuppoerYet: "لاتوجد رسائل",
          AppConfig.projectDetails: "تفاصيل المشروع",
          AppConfig.editMyProject: "تعديل المشروع",
          AppConfig.noData: "لاتوجد بيانات",
          AppConfig.send: "ارسال",
          AppConfig.exitApp: "الخروج من التطبيق",
          AppConfig.chat: "دردشة",
          AppConfig.myProject: "مشاريعي",
          AppConfig.project: "مشروع",
          AppConfig.price: "السعر",
          AppConfig.descreiption: "الوصف",
          AppConfig.days: "الايام",
          AppConfig.home: "الرئيسية",
          AppConfig.settings: "الاعدادات",
          AppConfig.agreeTotermsOfServices:
              "من خلال التسجيل في التطبيق، فإنك توافق على",
          AppConfig.lastName: "الاسم الاخير",
          AppConfig.firstName: "الاسم الاول",
          AppConfig.signUpWithEmail: "التسجيل عن طريق البريد الإلكتروني",
          AppConfig.timeOut: "يبدو ان اتصال الانترنت لديك ضعيف",
          AppConfig.tryAgain: "اعادة المحاولة",
          AppConfig.login: "تسجيل الدخول",
          AppConfig.chooseCategory: "",
          AppConfig.history: "",
          AppConfig.paymentHistory: "",
          AppConfig.businessFair: "",
          AppConfig.reviews: "",
          AppConfig.personalProfile: "",
          AppConfig.servicesDetail: "",
          AppConfig.subServices: "",
          AppConfig.faq: "",
          AppConfig.logout: "",
          AppConfig.privacyPolicy: "",
          AppConfig.termsOfServices: "",
          AppConfig.version: "",
          AppConfig.profile: "",
          AppConfig.noProjectYet: "",
          AppConfig.search: "",
          AppConfig.allOffer: "",
          AppConfig.addOffer: "",
          AppConfig.sendMessage: "",
          AppConfig.submitYourProject: "",
          AppConfig.seeAll: "عرض الكل",
          AppConfig.topEngineerRating: "الأعلي تقييم",
          AppConfig.populerServices: "الأقسام الرئيسية",
        },
        "en": {
          AppConfig.appName: "App Name",
          AppConfig.engineer: "",
          AppConfig.projectOwner: "",
          AppConfig.emal: "",
          AppConfig.phone: "",
          AppConfig.password: "",
          AppConfig.comfirmPassword: "",
          AppConfig.signUp: "",
          AppConfig.forgetPassword: "",
          AppConfig.tabScreen: "",
          AppConfig.addProjectScreen: "",
          AppConfig.addProtofilo: "",
          AppConfig.offerScreen: "",
          AppConfig.paypal: "",
          AppConfig.visa: "",
          AppConfig.chatRoom: "",
          AppConfig.addSomeProject: "",
          AppConfig.notifcation: "",
          AppConfig.profileUser: "",
          AppConfig.profileEngineer: "",
          AppConfig.support: "",
          AppConfig.language: "",
          AppConfig.noMessageYet: "",
          AppConfig.noMessageSuppoerYet: "",
          AppConfig.projectDetails: "",
          AppConfig.editMyProject: "",
          AppConfig.noData: "",
          AppConfig.send: "",
          AppConfig.exitApp: "",
          AppConfig.chat: "",
          AppConfig.myProject: "",
          AppConfig.project: "",
          AppConfig.price: "",
          AppConfig.descreiption: "",
          AppConfig.days: "",
          AppConfig.home: "",
          AppConfig.settings: "",
          AppConfig.agreeTotermsOfServices: "",
          AppConfig.lastName: "",
          AppConfig.firstName: "",
          AppConfig.signUpWithEmail: "",
          AppConfig.timeOut: "",
          AppConfig.tryAgain: "",
          AppConfig.login: "",
          AppConfig.chooseCategory: "",
          AppConfig.history: "",
          AppConfig.paymentHistory: "",
          AppConfig.businessFair: "",
          AppConfig.reviews: "",
          AppConfig.personalProfile: "",
          AppConfig.servicesDetail: "",
          AppConfig.subServices: "",
          AppConfig.faq: "",
          AppConfig.logout: "",
          AppConfig.privacyPolicy: "",
          AppConfig.termsOfServices: "",
          AppConfig.version: "",
          AppConfig.profile: "",
          AppConfig.noProjectYet: "",
          AppConfig.search: "",
          AppConfig.allOffer: "",
          AppConfig.addOffer: "",
          AppConfig.sendMessage: "",
          AppConfig.submitYourProject: "",
          AppConfig.seeAll: "",
          AppConfig.topEngineerRating: "",
          AppConfig.populerServices: "",
        },
      };
}
/* 


*/